COPY (
  SELECT
     COUNT(*) AS row_count
    ,MIN(NULLIF(ARRIVALDATE, '1900-01-01')) AS MIN_ARRIVALDATE
    ,MAX(NULLIF(ARRIVALDATE, '1900-01-01')) AS MAX_ARRIVALDATE
    ,MIN(NULLIF(SUSLDDATE, '1900-01-01')) AS MIN_SUSLDDATE
    ,MAX(NULLIF(SUSLDDATE, '1900-01-01')) AS MAX_SUSLDDATE
  FROM hes_ae
) TO 'hes_ae_date_range.json';