default:
  id: ae
  raw_data_dir: "C:/Users/Administrator/curedplus-raw-data/ae"
  staging_dir: "C:/Users/Administrator/curedplus-staging/ae"
  metadata_path: "C:/Users/Administrator/curedplus-raw-data/HES+TOS+V1.15.xlsx"
  sheet: HES AE TOS
  patient_key: token_person_id
