default:
  id: apc
  raw_data_dir: "C:/Users/Administrator/curedplus-raw-data/apc"
  staging_dir: "C:/Users/Administrator/curedplus-staging/apc"
  metadata_path: "C:/Users/Administrator/curedplus-raw-data/HES+TOS+V1.15.xlsx"
  sheet: HES APC TOS
  patient_key: token_person_id

development:
  raw_data_dir: "C:\\temp\\curedplus\\data\\apc\\raw"
  staging_dir: "C:\\temp\\curedplus\\data\\apc\\staging"
