default:
  id: hes_apc
  raw_data_dir: "C:\\Users\\Administrator\\curedplus-raw-data\\nhs\\HES_APC"
  staging_dir: "C:\\Users\\Administrator\\curedplus-staging\\apc"
  patient_key: token_person_id

development:
  raw_data_dir: "C:\\temp\\curedplus\\data\\apc\\raw"
  staging_dir: "C:\\temp\\curedplus\\data\\apc\\staging"
