# CUREd+ data pipeline configuration file
default:
  # Patient ID bridge file path
  patient_path: "C:/Users/Administrator/curedplus-raw-data/patient.csv"
  # Patient demographics data file path
  demographics_path: "C:/Users/Administrator/curedplus-raw-data/pd.parquet"
  # Log level https://daroczig.github.io/logger/reference/log_levels.html
  log_threshold: INFO
  # The output directory to save clean data files.
  log_dir: "C:\\Users\\Administrator\\curedplus-logs"
  # The output directory to save clean data files.
  clean_dir: "C:\\Users\\Administrator\\curedplus-clean-data"

# Alternative options for development
development:
  patient_path: "C:\\temp\\curedplus\\data\\patient_id_bridge.csv"
  demographics_path: "C:\\temp\\curedplus\\data\\pd.parquet"
  log_dir: "C:\\temp\\curedplus\\logs"

ubuntu:
  patient_path: ~/data/patients.parquet
  demographics_path: ~/data/pd.parquet
  log_dir: ~/curedplus-logs
  clean_dir: ~/curedplus-clean-data
